(define tva 00.2)
(define (prixttc1)
  (define ht (read))
  (display "Prix HT  : ")(display ht)
  (newline)
  (display "TVA      : ")(display tva)
  (newline)
  (display "----------------------")
  (newline)
  (display "Prix TTC : ") (display (* ht (+ 1 tva) ) )
  )
(prixttc1)