#pragma config(Sensor, S1,     tactileAv,      sensorTouch)
#pragma config(Sensor, S2,     tactileAr,      sensorTouch)
#pragma config(Sensor, S3,     captLumi,       sensorLightActive)
#pragma config(Sensor, S4,     ultraSon,       sensorSONAR)
#pragma config(Motor,  motorA,          mPince,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          mDroit,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          mGauche,       tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define entraxe 110  // mm
#define diamRoue 56 // mm
#define avant 1
#define arriere -1
#define gauche 0
#define droite 1


void tourner( int direction , int sens , int angleRot , int puisssance){
	  long p;
	  p = (( 2 * (long)entraxe * angleRot) / diamRoue );
    if ((( direction == droite ) & ( sens == avant )) || (( direction == gauche &  sens == arriere )))
    {
    	nMotorEncoder[mGauche] = 0;
      motor[mGauche] = 30 * sens;
      while (  nMotorEncoder[mGauche] * sens <= p )
      {
      }
      motor[mGauche] = 0;
      nMotorEncoder[mGauche] = 0;
    }
    else  //cas ou on veut tourner en avant et a gauche
    {
    	nMotorEncoder[mDroit] = 0;
      motor[mDroit] = 30 * sens;
      while (  nMotorEncoder[mDroit] * sens <= p )
      {
      }
      motor[mDroit] = 0;
      nMotorEncoder[mDroit] = 0;
    }
}

task main()
{
  tourner(  droite , avant , 180 , 30);
}
