#pragma config(Sensor, S1,     tactileAv,      sensorTouch)
#pragma config(Sensor, S2,     tactileAr,      sensorTouch)
#pragma config(Sensor, S3,     captLumi,       sensorLightActive)
#pragma config(Sensor, S4,     ultraSo,        sensorSONAR)
#pragma config(Motor,  motorA,          mPince,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          mDroit,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          mGauche,       tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


int CalculSeuil(){
	int sB;
	int sN;
	nxtDisplayStringAt(0,30,"poser sur blanc");
	while(nNxtButtonPressed != kEnterButton)
	  {}
	while(nNxtButtonPressed == kEnterButton)
	  {}
	sB = SensorValue(captLumi);
	eraseDisplay();
	nxtDisplayStringAt(0,30,"poser sur noir");
	while(nNxtButtonPressed != kEnterButton)
	  {}
	while(nNxtButtonPressed == kEnterButton)
	 {}
	sN = SensorValue(captLumi);
	eraseDisplay();
	return (sB+sN)/2;

}


task main () {
 int Vseuil;
 Vseuil = CalculSeuil();
 nxtDisplayStringAt(0,30,"robot pret?");
 while(nNxtButtonPressed != kEnterButton)
	  {}
 while(nNxtButtonPressed == kEnterButton)
	  {}
 motor[mDroit] = 30;
 motor[mGauche] = 30;
 while(SensorValue(captLumi)>= Vseuil)
   {}
 motor[mDroit] = 0;
 motor[mGauche] = 0;


}
