#pragma config(Sensor, S1,     tactileAv,      sensorTouch)
#pragma config(Sensor, S2,     tactileAr,      sensorTouch)
#pragma config(Sensor, S3,     captLumi,       sensorLightActive)
#pragma config(Sensor, S4,     ultraSo,        sensorSONAR)
#pragma config(Motor,  motorA,          mPince,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          mDroit,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          mGauche,       tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#define temps 5

int CalculSeuil(){
	int sB;
	int sN;
	nxtDisplayStringAt(0,30,"poser sur blanc");
	while(nNxtButtonPressed != kEnterButton)
	  {}
	while(nNxtButtonPressed == kEnterButton)
	  {}
	sB = SensorValue(captLumi);
	eraseDisplay();
	nxtDisplayStringAt(0,30,"poser sur noir");
	while(nNxtButtonPressed != kEnterButton)
	  {}
	while(nNxtButtonPressed == kEnterButton)
	 {}
	sN = SensorValue(captLumi);
	eraseDisplay();
	return (sB+sN)/2;

}


task main()
{
	int seuil;
  seuil = CalculSeuil();
  nxtDisplayStringAt(0,30,"robot pret?");
  while(nNxtButtonPressed != kEnterButton)
	  {}
  while(nNxtButtonPressed == kEnterButton)
	  {}
  ClearTimer(T1);
	while(time1[T1] <= (temps*1000)){
		if (SensorValue(captLumi) <= seuil)
		{
			motor[mGauche] = 0;
			motor[mDroit] = 30;
	  }
	  else
	  {
	  	motor[mDroit] = 0;
	  	motor[mGauche] = 30;
	  }

	}

	motor[mDroit] = 0;
	motor[mGauche] = 0;

}
