#pragma config(Sensor, S1,     tactileAv,      sensorTouch)
#pragma config(Sensor, S2,     tactileAr,      sensorTouch)
#pragma config(Sensor, S3,     captLumi,       sensorLightActive)
#pragma config(Sensor, S4,     ultraSo,        sensorSONAR)
#pragma config(Motor,  motorA,          mPince,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          mDroit,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          mGauche,       tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#define temps 5

int CalculSeuil(){
	int sB;
	int sN;
	nxtDisplayStringAt(0,30,"poser sur blanc");
	while(nNxtButtonPressed != kEnterButton)
	  {}
	while(nNxtButtonPressed == kEnterButton)
	  {}
	sB = SensorValue(captLumi);
	eraseDisplay();
	nxtDisplayStringAt(0,30,"poser sur noir");
	while(nNxtButtonPressed != kEnterButton)
	  {}
	while(nNxtButtonPressed == kEnterButton)
	 {}
	sN = SensorValue(captLumi);
	eraseDisplay();
	return (sB+sN)/2;

}

task main()
{
	int Vseuil;
	bool vuBlanc;
	int cpt;
  Vseuil = CalculSeuil();
  vuBlanc = true;
  ClearTimer(T1);
  cpt = 0;
  motor[mDroit] = 30;
  motor[mGauche] = 30;
  while(time1[T1] <= (temps*1000)){
  	if (SensorValue(captLumi) < Vseuil){
  		if (vuBlanc) {
  			cpt = cpt+1;
  			vuBlanc = false;
  	  }
  	}
  	 else
  	  {
  	  	vuBlanc = true;
  	  }

 }
 motor[mDroit] = 0;
 motor[mGauche] = 0;
 nxtDisplayStringAt(0,30,"nb de coup %d",cpt);
 wait1Msec(temps*1000);

}
