#pragma config(Sensor, S1,     tactileAvant,   sensorTouch)
#pragma config(Sensor, S2,     tactileArriere, sensorTouch)
#pragma config(Sensor, S3,     CaptLumi,       sensorLightActive)
#pragma config(Sensor, S4,     Ultrason,       sensorSONAR)
#pragma config(Motor,  motorA,          mPince,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          mDroit,       tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          mGauche,        tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#define seuil 50

void OuvrirPince(int deg, int puissance )
{
	nMotorEncoder[mPince]= 0;
	motor [mPince] = puissance;
	while (nMotorEncoder[mPince] < deg)
	{

 	}
 	motor [mPince] = 0;
}

void FermerPince(int deg, int puissance )
{
	nMotorEncoder[mPince]= 0;
	motor [mPince] = puissance*(-1);
	while (nMotorEncoder[mPince]*(-1) < deg)
	{

 	}
 	motor [mPince] = 0;
}


task main()
{
	OuvrirPince(35, 25);
	motor [mGauche] = 30;
	motor [mDroit] = 30;

	while (SensorValue (CaptLumi) > seuil){

	}
	motor [mGauche] = 0;
	motor [mDroit] = 0;
}
