#pragma config(Sensor, S1,     tactileAvant,   sensorTouch)
#pragma config(Sensor, S2,     tactileArriere, sensorTouch)
#pragma config(Sensor, S3,     CaptLumi,       sensorLightActive)
#pragma config(Sensor, S4,     Ultrason,       sensorSONAR)
#pragma config(Motor,  motorA,          mPince,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          mGauche,       tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          mDroit,        tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#define seuil 50

task main()
{

	motor [mGauche] = 30;
	motor [mDroit] = 30;
	while (SensorValue (CaptLumi) > seuil){

	}
	motor [mGauche] = 0;
	motor [mDroit] = 0;
}
