#pragma config(Sensor, S1,     tactileAvant,   sensorTouch)
#pragma config(Sensor, S2,     tactileArriere, sensorTouch)
#pragma config(Sensor, S3,     CaptLumi,       sensorLightActive)
#pragma config(Sensor, S4,     Ultrason,       sensorSONAR)
#pragma config(Motor,  motorA,          mPince,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          mDroit,       tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          mGauche,        tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void OuvrirPince(int deg, int puissance )
{
	nMotorEncoder[mPince]= 0;
	motor [mPince] = puissance;
	while (nMotorEncoder[mPince] < deg)
	{

 	}
 	motor [mPince] = 0;
}

void FermerPince(int deg, int puissance )
{
	nMotorEncoder[mPince]= 0;
	motor [mPince] = puissance*(-1);
	while (nMotorEncoder[mPince]*(-1) < deg)
	{

 	}
 	motor [mPince] = 0;
}

task main()
{
	OuvrirPince(35, 25);
	motor [mGauche] = 30;
	motor [mDroit] = 30;
	while (SensorValue (tactileAvant) != 1){

	}

	motor [mGauche] = 0;
	motor [mDroit] = 0;
	FermerPince (35, 25);
	wait1Msec (1000);

	nMotorEncoder[motorC]= 0;
	motor [mGauche] = -30;
	motor [mDroit] = -30;
	while (nMotorEncoder[motorC]*(-1) < 1*360){

	}
	motor [mGauche] = 0;
	motor [mDroit] = 0;
	OuvrirPince(35, 25);
}
