#pragma config(Sensor, S1,     tactileAvant,   sensorTouch)
#pragma config(Sensor, S2,     tactileArriere, sensorTouch)
#pragma config(Sensor, S3,     CaptLumi,       sensorLightActive)
#pragma config(Sensor, S4,     Ultrason,       sensorSONAR)
#pragma config(Motor,  motorA,          mPince,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          mGauche,       tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          mDroit,        tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#define nbRot1 3
#define nbRot2 3

task main()
{
	nMotorEncoder[motorC]= 0;
	motor [mGauche] = 30;
	motor [mDroit] = 30;
	while (nMotorEncoder[motorC] < nbRot1*360){

	}
	motor [mGauche] = 0;
	motor [mDroit] = 0;

	nMotorEncoder[motorC]= 0;
	motor [mGauche] = -30;
	motor [mDroit] = -30;
	while (nMotorEncoder[motorC]*(-1) < nbRot2*360){

	}
	motor [mGauche] = 0;
	motor [mDroit] = 0;
}
