#pragma config(Sensor, S1,     tactileAvant,   sensorTouch)
#pragma config(Sensor, S2,     tactileArriere, sensorTouch)
#pragma config(Sensor, S3,     CaptLumi,       sensorLightActive)
#pragma config(Sensor, S4,     Ultrason,       sensorSONAR)
#pragma config(Motor,  motorA,          mPince,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          mDroit,       tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          mGauche,        tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
nMotorEncoder[motorC]= 0;
	motor [mGauche] = 30;
	motor [mDroit] = 30;
while (nMotorEncoder[motorC] <= 2*360){

}
motor [mGauche] = 0;
motor [mDroit] = 0;




}
