#pragma config(Sensor, S1,     tactileAvant,   sensorTouch)
#pragma config(Sensor, S2,     tactileArriere, sensorTouch)
#pragma config(Sensor, S3,     CaptLumi,       sensorLightActive)
#pragma config(Sensor, S4,     Ultrason,       sensorSONAR)
#pragma config(Motor,  motorA,          mPince,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          mDroit,       tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          mGauche,        tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#define diamRoue 56
#define entraxe 115
#define distance 400 // mm

void avancerDistance (int D, int puissance)
{
	long conversion;
	conversion = ((long)D * 360) /( PI * diamRoue);

			nMotorEncoder[mDroit] = 0;
			motor[mDroit] =30;
			motor[mGauche] = 30;
			while ( nMotorEncoder[mDroit] <= conversion)
			{
			}
			motor[mGauche] = 0;
			motor[mDroit] = 0;

}


task main()
{
	avancerDistance(distance, 30);
}
