#pragma config(Sensor, S1,     tactileAvant,   sensorTouch)
#pragma config(Sensor, S2,     tactileArriere, sensorTouch)
#pragma config(Sensor, S3,     CaptLumi,       sensorLightActive)
#pragma config(Sensor, S4,     Ultrason,       sensorSONAR)
#pragma config(Motor,  motorA,          mPince,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          mDroit,       tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          mGauche,        tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#define diamRoue 56
#define entraxe 115
#define D 400 // mm
#define temps 2000 // 2 secondes
#define Angle 180

void avancerTemps (int time, int puissance, int angleRot)
{
	long mdeg;
	mdeg = ((long)angleRot * 2* entraxe) / (diamRoue);

			nMotorEncoder[mDroit] = 0;
			nMotorEncoder[mGauche] = 0;
			motor[mDroit] =30;
			motor[mGauche] = 30;

			wait1Msec(time);

			motor[mDroit] = 0;
			motor[mGauche] = 0;

			wait1Msec(1000);

			motor[mDroit] =30;
			while ( nMotorEncoder[mDroit] <= mdeg)
			{
			}
				motor[mDroit] = 0;
}


task main()
{
	avancerTemps(temps, 30, Angle);
}
